//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestPfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class combzanatye
    {
        public int idCombZanatye { get; set; }
        public Nullable<int> NumbOfComb { get; set; }
        public string NameComb { get; set; }
    }
}
