//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestPfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupinzanatye
    {
        public int idGroupInZanatye { get; set; }
        public Nullable<int> id_group { get; set; }
    }
}
