//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestPfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class raspisanie
    {
        public int id_raspisanie { get; set; }
        public Nullable<int> id_user { get; set; }
        public string predmetname { get; set; }
        public string auditoria { get; set; }
        public Nullable<bool> verh { get; set; }
        public Nullable<bool> niz { get; set; }
        public Nullable<bool> edinozdy { get; set; }
        public Nullable<bool> practice { get; set; }
        public Nullable<System.TimeSpan> timeb { get; set; }
        public string raspisaniecol { get; set; }
    
        public virtual user_table user_table { get; set; }
    }
}
