//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestPfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class spisokinzanatye
    {
        public int idSpisokInZanatyae { get; set; }
        public Nullable<int> id_students_group { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<bool> propusk { get; set; }
    }
}
