//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestPfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class students_group
    {
        public int id_students_group { get; set; }
        public Nullable<int> id_group { get; set; }
        public string name_s { get; set; }
    
        public virtual groups groups { get; set; }
    }
}
