//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestPfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zanatye
    {
        public int idZanatye { get; set; }
        public Nullable<int> idGroupInZanatye { get; set; }
        public Nullable<int> id_raspisanie { get; set; }
        public Nullable<int> idSpisokInZanatye { get; set; }
        public Nullable<System.DateTime> timeday { get; set; }
        public Nullable<bool> modul { get; set; }
        public Nullable<int> idCombZanatye { get; set; }
    }
}
